language: node_js
sudo: false
addons:
  code_climate:
    repo_token: 83664567837c2e1a63f2d6cb31e0873d99852a439474adb2fd2277458178f94b
  postgresql: "9.4"
node_js:
- '6'
global:
  - CF_USERNAME_DEV=11ecac35-43fe-4b1a-ba03-1dca9d72b806
  - CF_USERNAME_PROD=50f7a885-084a-495a-8adf-7c6ab003d79f
cache:
  directories:
  - node_modules
env:
- PORT=21517 DATABASE_URL="postgres://postgres:@localhost/travis_ci_test" SUDS_API_URL="http://localhost:21517/mocks"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
script:
- npm run dba
- npm run lint
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive
- codecov
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    script: "./cg-deploy/deploy.sh fs-api-prod"
    skip_cleanup: true
    on:
      repo: 18F/fs-middlelayer-api
      branch: master
  - provider: script
    script: "./cg-deploy/deploy.sh fs-api-staging"
    skip_cleanup: true
    on:
      repo: 18F/fs-middlelayer-api
      branch: dev
