language: node_js
sudo: false
addons:
  code_climate:
    repo_token: 83664567837c2e1a63f2d6cb31e0873d99852a439474adb2fd2277458178f94b
  postgresql: "9.4"
node_js:
- '6'
global:
  - CF_USERNAME_DEV=11ecac35-43fe-4b1a-ba03-1dca9d72b806
  - CF_USERNAME_PROD=50f7a885-084a-495a-8adf-7c6ab003d79f
cache:
  directories:
  - node_modules
env:
- PORT=21517 DATABASE_URL="postgres://postgres:@localhost/travis_ci_test" SUDS_API_URL="http://localhost:21517/mocks"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
script:
- npm run dba
- npm run lint
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive
- codecov
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: heroku
    api_key:
      secure: UcbT1SQYR5lFlAAwTszr7QXVRp4ofKXeIsNzDmrfqu4P96fb+H3iD3ikxP+5SAtEkCYPN8xnaHE0H2V+fk4+1TTUruPIlXtGdCKTlxjTz2I3oqB4Qb1THeqYUbmSlK6pRh83bvr8Nl0WgEtnd8uzERroL+srWYNSH8A6mvsaO/TGADEnrUFo9pp7uTtgyVj/MLrKn/7xQJsLtyPHUMHSY8cvDv9TZLiUkA/9gFvFI8DPVD4whQBFHc+iOWYOCBN3QGrAS3lDwLvFSZm4nR5XE/AiFTLkVnYHQnYcf3DiQooWjdrWqwzNumpbRhDA0ybMNBHwY3+qFl6eObnhpubvCNMRQjYlZ5On5DdUXKX3AB2YoVKues6D4Na30agafRHM8RNal9Tgcj/mHxtN/lNMlA2gZgyLSaTN/VTbSYE+rildnnfqGY6+zJhPoza3r3C3IGwThhJB6su2YhQi9GqRlX4XtwjKJOQDJy2TTEhzjA5n5qqKHM9wdvoeSkjxpGN5gQThhcci60MFKy5Zys0N9hOdbOQWm48rUbCYI3eC75QiCCER29D9EUGTAVWN+x7Gp6LBsGpbaXOuTihxTBwV8DMI13T9GhCIRKtL47G6HZ/2N34WXqISCVpZjw+fLYsAw9YtYNX2fneCDa879u8f+Jqae5inLe/qulAk8PTzEY4=
    run:
      - "npm run dba"
    app:
      master: fs-epermit-st
      dev: fs-epermit-dev
    on:
      repo: nci-ats/fs-middlelayer-api
  - provider: script
    script: "./cg-deploy/deploy.sh fs-api-prod"
    skip_cleanup: true
    on:
      repo: 18F/fs-middlelayer-api
      branch: master
  - provider: script
    script: "./cg-deploy/deploy.sh fs-api-staging"
    skip_cleanup: true
    on:
      repo: 18F/fs-middlelayer-api
      condition: ${TRAVIS_BRANCH:0:7} = "sprint-"
